include: ['_pages', '_styles', '_images']

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  sass_dir: _sass
  style: compact